name: Test

on:
  push:
    tags:
    - "[0-9]+.[0-9]+.[0-9]+"

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-dotnet@v4
    
    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build -c Release --no-restore

    - name: L1
      run: bash -c "ls ."

    - name: L1
      run: bash -c "ls ./src"

    # - name: L3
    #   run: bash -c "ls ./artifacts"

    # - name: L4
    #   run: bash -c "ls ./artifacts/bin"

    # - name: L5
    #   run: bash -c "ls ./artifacts/bin"

    - name: Test
      run: dotnet test -c Release --no-build
    
    - name: Pack
      run: dotnet pack
 
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - name: Dump job context
      env:
        JOB_CONTEXT: ${{ toJson(job) }}
      run: echo "$JOB_CONTEXT"
    # - name: Publish to GPR
    #   run: dotnet nuget push "./artifacts/package/release/*.nupkg" -k ${{ secrets.YOUR_NUGET_KEY }}
