name: Test

on:
  push:
    tags:
    - "[0-9]+.[0-9]+.[0-9]+"

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-dotnet@v4
    
    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build -c Release --no-restore

    - name: Test
      run: dotnet test -c Release --no-build
    
    - name: Pack
      run: dotnet pack
 
    - name: Version (from tag)
      env:
        VERSION: ${{ github.ref_name }}
      run: echo "$VERSION"
    # - name: Publish to GPR
    #   run: dotnet nuget push "./artifacts/package/release/*.nupkg" -k ${{ secrets.YOUR_NUGET_KEY }}
