name: Test

on:
  push:
    tags:
    - "[0-9]+.[0-9]+.[0-9]+"

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      id-token: write

    steps:
    - uses: actions/checkout@v7
    - uses: actions/setup-dotnet@v6
    
    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build -c Release --no-restore

    - name: Test
      run: dotnet test -c Release --no-build
    
    - name: Pack
      run: dotnet pack

    - name: Nuget login
      uses: Nuget/login@v1
      id: login
      with:
        user: Martin521
 
    - name: Push to nuget.org
      env:
        VERSION: ${{ github.ref_name }}
      run: dotnet nuget push "./artifacts/package/release/runfs.${VERSION}.nupkg"
        --source https://api.nuget.org/v3/index.json
        --api-key ${{steps.login.outputs.NUGET_API_KEY}}
